# Generated by Django 5.1.2 on 2026-10-02 16:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_asset', models.CharField(blank=True, max_length=200, verbose_name='مسیر تصویر قالب')),
                ('image_upload', models.ImageField(blank=True, upload_to='images/', verbose_name='تصویر بارگذاری\u200cشده')),
                ('image_alt', models.CharField(blank=True, max_length=250, verbose_name='متن جایگزین تصویر')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=180, unique=True, verbose_name='شناسهٔ نشانی')),
                ('category', models.CharField(choices=[('residential', 'معماری مسکونی'), ('interior', 'طراحی داخلی'), ('landscape', 'محوطه\u200cسازی'), ('workplace', 'فضاهای کاری'), ('public', 'فضاهای عمومی')], max_length=20, verbose_name='دسته\u200cبندی')),
                ('jalali_date', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{4}-\\d{2}-\\d{2}$', 'قالب تاریخ باید YYYY-MM-DD باشد.')], verbose_name='تاریخ شمسی برای مرتب\u200cسازی (YYYY-MM-DD)')),
                ('date_display', models.CharField(max_length=50, verbose_name='تاریخ نمایشی')),
                ('reading_minutes', models.PositiveSmallIntegerField(default=5, verbose_name='زمان مطالعه (دقیقه)')),
                ('body_html', models.TextField(blank=True, verbose_name='متن و HTML مقاله')),
                ('download_file', models.FileField(blank=True, upload_to='downloads/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'odt'])], verbose_name='فایل دانلود مقاله')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقاله\u200cها',
                'ordering': ['-jalali_date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('subject', models.CharField(choices=[('اجرای ساختمان', 'اجرای ساختمان'), ('طراحی ساختمان', 'طراحی ساختمان'), ('نگهداری', 'نگهداری'), ('مشارکت در ساخت', 'مشارکت در ساخت'), ('سایر', 'سایر')], max_length=30, verbose_name='موضوع')),
                ('message', models.TextField(blank=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('contacted', 'تماس گرفته شد'), ('closed', 'بسته شد')], default='new', max_length=20, verbose_name='وضعیت')),
                ('admin_notes', models.TextField(blank=True, verbose_name='یادداشت داخلی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
            ],
            options={
                'verbose_name': 'درخواست مشاوره',
                'verbose_name_plural': 'درخواست\u200cهای مشاوره',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_asset', models.CharField(blank=True, max_length=200, verbose_name='مسیر تصویر قالب')),
                ('image_upload', models.ImageField(blank=True, upload_to='images/', verbose_name='تصویر بارگذاری\u200cشده')),
                ('image_alt', models.CharField(blank=True, max_length=250, verbose_name='متن جایگزین تصویر')),
                ('title', models.CharField(max_length=160, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='شناسهٔ نشانی')),
                ('category', models.CharField(choices=[('residential', 'مسکونی'), ('commercial', 'تجاری'), ('landscape', 'محوطه\u200cسازی')], max_length=20, verbose_name='نوع پروژه')),
                ('location', models.CharField(max_length=100, verbose_name='موقعیت')),
                ('year_text', models.CharField(blank=True, max_length=30, verbose_name='سال اجرا')),
                ('area_text', models.CharField(blank=True, max_length=100, verbose_name='متراژ')),
                ('body_html', models.TextField(blank=True, verbose_name='متن و HTML شرح پروژه')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('featured_order', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='جایگاه صفحهٔ اصلی')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه\u200cها',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='تهران، خیابان ولیعصر', max_length=200, verbose_name='نشانی')),
                ('phone_display', models.CharField(default='۰۲۱–۸۸۰۰ ۰۰۰۰', max_length=50, verbose_name='شمارهٔ نمایشی')),
                ('phone_href', models.CharField(default='+982188000000', max_length=30, verbose_name='شمارهٔ تماس بین\u200cالمللی')),
                ('email', models.EmailField(default='hello@paksarakaren.example', max_length=254, verbose_name='ایمیل')),
            ],
            options={
                'verbose_name': 'اطلاعات تماس سایت',
                'verbose_name_plural': 'اطلاعات تماس سایت',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_asset', models.CharField(blank=True, max_length=200, verbose_name='مسیر تصویر قالب')),
                ('image_upload', models.ImageField(blank=True, upload_to='images/', verbose_name='تصویر بارگذاری\u200cشده')),
                ('image_alt', models.CharField(blank=True, max_length=250, verbose_name='متن جایگزین تصویر')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('role', models.CharField(max_length=100, verbose_name='سمت')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نمایش در سایت')),
            ],
            options={
                'verbose_name': 'عضو تیم',
                'verbose_name_plural': 'اعضای تیم',
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_asset', models.CharField(blank=True, max_length=200, verbose_name='مسیر تصویر قالب')),
                ('image_upload', models.ImageField(blank=True, upload_to='images/', verbose_name='تصویر بارگذاری\u200cشده')),
                ('image_alt', models.CharField(blank=True, max_length=250, verbose_name='متن جایگزین تصویر')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='core.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'تصویر گالری',
                'verbose_name_plural': 'تصاویر گالری',
                'ordering': ['position', 'pk'],
            },
        ),
    ]
