# Generated by Django 5.1.2 on 2026-10-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=180, unique=True, verbose_name='شناسهٔ نشانی'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=160, unique=True, verbose_name='شناسهٔ نشانی'),
        ),
    ]
